version: '3.8'

services:
  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      API_KEY: ${API_KEY}
      CLOUD_NAME: ${CLOUD_NAME}
      JDBC_DATABASE_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      JDBC_DATABASE_URL: ${JDBC_DATABASE_URL}
      JDBC_DATABASE_USERNAME: ${JDBC_DATABASE_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET}
      MAIL_FROM: ${MAIL_FROM}

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
      PGTZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: